"""allow_guest_login

Revision ID: 8f1b8e97d48f
Revises: 4ca9efd0f2a3
Create Date: 2026-01-05 23:39:38.531997

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f1b8e97d48f"
down_revision: Union[str, Sequence[str], None] = "4ca9efd0f2a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # FIX: Need handle now, set default server maybe a tech dept
    op.add_column(
        "user",
        sa.Column(
            "is_guest", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("user", "is_guest")
    # ### end Alembic commands ###
